Feat: add clamped Pockels calculation capability
bastonero/aiida-vibroscopy pull request #67
Opened 2024-06-13 09:20 UTC by vdemestral

I add the possibility of computing the clamped Pockels tensors into the `VibroMixing` class.

2024-06-13 14:31 UTC, bastonero commented on src/aiida_vibroscopy/calculations/spectra_utils.py
> +    phonopy_instance.run_qpoints(q_points=[0, 0, 0], nac_q_direction=q_reduced, with_eigenvectors=True)
```suggestion
    phonopy_instance.run_qpoints(q_points=[[0, 0, 0]], nac_q_direction=q_reduced, with_eigenvectors=True)
```

2024-06-13 14:32 UTC, bastonero requested changes
The code is awesome, thanks @vdemestral ! Just some minor changes!

2024-06-13 14:33 UTC, vdemestral commented on src/aiida_vibroscopy/calculations/spectra_utils.py
> +    phonopy_instance.run_qpoints(q_points=[0, 0, 0], nac_q_direction=q_reduced, with_eigenvectors=True)
Are you sure????

2024-11-22 15:04 UTC, bastonero commented
CLA bot

2024-11-29 14:03 UTC, bastonero approved these changes

2025-01-09 14:49 UTC, vdemestral commented
I have read the CLA Document and I hereby accept the CLA

2025-01-09 16:01 UTC, bastonero commented
recheck

2025-01-10 10:28 UTC, vdemestral commented
I have read the CLA Document and I hereby accept the CLA

2025-03-06 13:15 UTC, merged